"""Podman storage and image lifecycle for the OpenFOAM container.

Every podman invocation in Scentinel must run with the environment
:func:`podman_env` returns. That environment pins ``CONTAINERS_STORAGE_CONF`` to
a storage config living inside the app home, so pulling the solver image never
touches the user's default (``~/.local/share/containers``) storage. A screening
tool that silently consumes gigabytes of the user's home is not acceptable, and
a config file is the only knob podman offers that redirects both the image
graph and the run root without wrapping every call in a shell.

No storage driver is pinned on purpose: podman's rootless default (overlay) is
what we want, and ``vfs`` would copy every layer in full — gigabytes for this
image.

The pull-and-verify flow is exposed as :func:`setup_container` so the GUI, the
CLI (``python -m scentinel.core.container``), and ``scripts/setup_container.sh``
all share one implementation.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import threading
from collections.abc import Callable, Iterable, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path

from scentinel.core.casegen import FOAM_BASHRC, IMAGE

#: Tools the pipeline shells out to inside the image, in the order it uses them.
REQUIRED_TOOLS = ("gmshToFoam", "changeDictionary", "simpleFoam", "foamToVTK")

#: Exit code reported when a setup was cancelled before it ran to completion.
#: Same sentinel the runner uses for a cancelled solve.
CANCELLED_EXIT_CODE = -2

_STORAGE_CONF_HEADER = "# Generated by Scentinel. Do not edit.\n"

#: Verified by the setup step: the image entrypoint leaves a non-interactive
#: shell without the OpenFOAM environment on PATH, hence the explicit source.
VERIFY_SCRIPT = (
    f"source {FOAM_BASHRC} || exit 9; "
    f"for tool in {' '.join(REQUIRED_TOOLS)}; do "
    'command -v "$tool" >/dev/null 2>&1 || { echo "MISSING: $tool" >&2; exit 1; }; '
    'echo "  $tool OK"; '
    "done"
)


@dataclass
class ContainerSetupResult:
    """Outcome of a container setup attempt."""

    ok: bool
    exit_code: int
    log: list[str] = field(default_factory=list)


def app_home() -> Path:
    """Scentinel's own home directory, overridable via ``SCENTINEL_HOME``."""
    override = os.environ.get("SCENTINEL_HOME")
    if override:
        return Path(override).expanduser()
    return Path.home() / ".scentinel"


def storage_root() -> Path:
    """Where this app keeps all of its container storage."""
    return app_home() / "containers"


def storage_conf_path() -> Path:
    """The podman storage config that isolates the app's containers."""
    return storage_root() / "storage.conf"


def _fuse_overlayfs() -> str | None:
    """Path to ``fuse-overlayfs`` when it is installed, else ``None``."""
    return shutil.which("fuse-overlayfs")


def ensure_storage_conf() -> Path:
    """Write the isolated storage config, only when it is missing or stale.

    Returns the config path. Rewriting only on a difference keeps the mtime
    stable across the many podman calls a run makes.

    The overlay driver needs help in a *private* graphroot. ``podman run`` here
    uses ``--userns=keep-id`` so the container user matches the host user and
    the mounted case directory stays writable; with the native overlay driver
    that forces an ID-mapped copy of every layer, which fails with "creating an
    ID-mapped copy of layer" against a graphroot the user has not populated
    before. ``fuse-overlayfs`` performs that mapping in userspace, so it is
    selected when available. ``ignore_chown_errors`` covers the remaining
    ownership differences a rootless private store can present.
    """
    path = storage_conf_path()
    root = storage_root()
    mount_program = _fuse_overlayfs()
    text = f"{_STORAGE_CONF_HEADER}[storage]\n"
    if mount_program is not None:
        text += 'driver = "overlay"\n'
    text += f'graphroot = "{root / "storage"}"\nrunroot = "{root / "run"}"\n'
    if mount_program is not None:
        text += (
            "\n[storage.options]\n"
            'ignore_chown_errors = "true"\n'
            "\n[storage.options.overlay]\n"
            f'mount_program = "{mount_program}"\n'
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_text(encoding="utf-8") != text:
        path.write_text(text, encoding="utf-8")
    return path


def podman_env(base: Mapping[str, str] | None = None) -> dict[str, str]:
    """Environment every podman call must use.

    A copy of ``os.environ`` (or ``base``) with ``CONTAINERS_STORAGE_CONF``
    pointing at the app's own storage config. The config is written here, so it
    always exists before podman reads it.
    """
    env = dict(os.environ if base is None else base)
    env["CONTAINERS_STORAGE_CONF"] = str(ensure_storage_conf())
    return env


def podman_available() -> bool:
    return shutil.which("podman") is not None


def image_available(image: str = IMAGE) -> bool:
    """True when the solver image is already pulled into the app's storage."""
    if not podman_available():
        return False
    result = subprocess.run(
        ["podman", "image", "exists", image],
        capture_output=True,
        text=True,
        env=podman_env(),
    )
    return result.returncode == 0


def container_ready(image: str = IMAGE) -> tuple[bool, str]:
    """Whether the container can run right now, and why not when it cannot.

    Never raises: the UI calls this to decide whether Run is enabled, and a
    missing podman, an unwritable app home, or an unpulled image must all
    surface as a message rather than a traceback.
    """
    if not podman_available():
        return False, "podman is not installed"
    try:
        if not image_available(image):
            return False, f"container image {image} is not pulled"
    except OSError as error:
        return False, f"container storage is not usable: {error}"
    return True, ""


def _lines(value: object) -> list[str]:
    """Split captured output into lines.

    ``run`` is injectable, so the captured output may arrive as one string
    (``text=True``, what this module always asks for), as bytes, or already
    split; all three mean the same thing here.
    """
    if value is None:
        return []
    if isinstance(value, bytes):
        return value.decode("utf-8", "replace").splitlines()
    if isinstance(value, str):
        return value.splitlines()
    if isinstance(value, Iterable):
        return [str(line).rstrip("\n") for line in value]
    return [str(value)]


def setup_container(
    image: str = IMAGE,
    *,
    on_log: Callable[[str], None] | None = None,
    cancel: threading.Event | None = None,
    run: Callable[..., subprocess.CompletedProcess] = subprocess.run,
) -> ContainerSetupResult:
    """Pull ``image`` and verify the tools the pipeline calls.

    Each step's output is reported to ``on_log`` line by line, and the full log
    is returned either way. ``run`` is injectable (and defaults to
    ``subprocess.run``), so a step's output is captured rather than followed
    live: podman's progress for a step appears when that step returns.

    ``cancel`` cannot interrupt a podman call in flight — ``run`` takes no such
    argument — so it is checked between steps and the setup returns early once
    set.
    """
    log: list[str] = []

    def emit(line: str) -> None:
        log.append(line)
        if on_log is not None:
            on_log(line)

    def cancelled() -> bool:
        return cancel is not None and cancel.is_set()

    if cancelled():
        emit("Cancelled before start.")
        return ContainerSetupResult(ok=False, exit_code=CANCELLED_EXIT_CODE, log=log)

    try:
        env = podman_env()
    except OSError as error:
        emit(f"ERROR: cannot prepare container storage: {error}")
        return ContainerSetupResult(ok=False, exit_code=1, log=log)

    emit(f"==> Storage: {storage_root()}")
    steps = (
        (f"Pulling {image}", ["podman", "pull", image]),
        (
            "Verifying the tools the pipeline uses",
            ["podman", "run", "--rm", image, "bash", "-lc", VERIFY_SCRIPT],
        ),
    )
    for label, command in steps:
        if cancelled():
            emit("Cancelled.")
            return ContainerSetupResult(ok=False, exit_code=CANCELLED_EXIT_CODE, log=log)
        emit(f"==> {label}")
        try:
            result = run(
                command,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                env=env,
            )
        except OSError as error:
            emit(f"ERROR: {error}")
            return ContainerSetupResult(ok=False, exit_code=1, log=log)
        for line in _lines(result.stdout):
            emit(line)
        if result.returncode != 0:
            emit(f"ERROR: {label} failed with exit code {result.returncode}")
            return ContainerSetupResult(ok=False, exit_code=result.returncode, log=log)

    emit("==> Container ready")
    return ContainerSetupResult(ok=True, exit_code=0, log=log)


def main(argv: Sequence[str] | None = None) -> int:
    """CLI entry point used by ``scripts/setup_container.sh``.

    An image argument wins; otherwise ``SCENTINEL_IMAGE``, otherwise the
    catalogue default.
    """
    args = list(sys.argv[1:] if argv is None else argv)
    image = args[0] if args else (os.environ.get("SCENTINEL_IMAGE") or IMAGE)
    return 0 if setup_container(image, on_log=print).ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
