"""Auto-generated by scripts/build_gas_data.py. Do not edit by hand."""

# Data sources:
#   EPA AP-42 Ch.2.4 final (Aug 2024): docs/data/c2s4_2024_final.pdf
#   EPA AP-42 tables: docs/data/ap-42-chapter-2-section-4-tables-final.xlsx
#   EPA LMOP landfill gas basics: https://www.epa.gov/lmop/basic-information-about-landfill-gas

GAS_PROPERTIES = {
    "CO": {
        "name": "Carbon monoxide",
        "mw_g_mol": 28.01,
        "diffusivity_m2_s": 2e-05
    },
    "CH4": {
        "name": "Methane",
        "mw_g_mol": 16.04,
        "diffusivity_m2_s": 2.2e-05
    },
    "VOC": {
        "name": "Non-methane organic compounds (as hexane proxy)",
        "mw_g_mol": 86.18,
        "diffusivity_m2_s": 8.7e-06
    },
    "H2S": {
        "name": "Hydrogen sulfide",
        "mw_g_mol": 34.08,
        "diffusivity_m2_s": 1.6e-05
    }
}

SOURCE_DEFAULTS = {
    "CO": {
        "conc_ppmv": 105,
        "basis": "AP-42 Final Factors: uncontrolled CO, parts per million (ref 98)",
        "rating": "Minimally representative"
    },
    "CH4": {
        "fraction_by_volume": 0.5,
        "basis": "EPA LMOP: LFG ~50% CH4 by volume",
        "alternate_fraction": 0.55,
        "alternate_basis": "AP-42 Ch.2.4 steady-state: ~55% CH4, 40% CO2, 5% N2"
    },
    "VOC": {
        "conc_ppmv": 550,
        "basis": "AP-42 Table 2.4-2: NMOC as hexane, no/unknown co-disposal, 1992+",
        "alternate_conc_ppmv": 2400,
        "alternate_basis": "AP-42 Table 2.4-2: NMOC as hexane, co-disposal (pre 1992)"
    },
    "H2S": {
        "conc_ppmv": 36,
        "basis": "AP-42 Table 2.4-1: default concentration",
        "rating": "B"
    }
}

AP42_TRACE_COMPOUNDS = {
    "Compound": {
        "mw_g_mol": "Molecular Weight",
        "conc_ppmv": "Default Concentration (ppmv)",
        "rating": "Emission Factor Rating"
    },
    "1,1,1-Trichloroethane (methyl chloroform)a": {
        "mw_g_mol": 133.41,
        "conc_ppmv": 0.48,
        "rating": "B"
    },
    "1,1,2,2-Tetrachloroethanea": {
        "mw_g_mol": 167.85,
        "conc_ppmv": 1.1,
        "rating": "C"
    },
    "1,1-Dichloroethane (ethylidene dichloride)a": {
        "mw_g_mol": 98.97,
        "conc_ppmv": 2.4,
        "rating": "B"
    },
    "1,1-Dichloroethene (vinylidene chloride)a": {
        "mw_g_mol": 96.94,
        "conc_ppmv": 0.2,
        "rating": "B"
    },
    "1,2-Dichloroethane (ethylene dichloride)a": {
        "mw_g_mol": 98.96,
        "conc_ppmv": 0.41,
        "rating": "B"
    },
    "1,2-Dichloropropane (propylene dichloride)a": {
        "mw_g_mol": 112.99,
        "conc_ppmv": 0.18,
        "rating": "D"
    },
    "2-Propanol (isopropyl alcohol)": {
        "mw_g_mol": 60.11,
        "conc_ppmv": 50,
        "rating": "E"
    },
    "Acetone": {
        "mw_g_mol": 58.08,
        "conc_ppmv": 7,
        "rating": "B"
    },
    "Acrylonitrilea": {
        "mw_g_mol": 53.06,
        "conc_ppmv": 6.3,
        "rating": "D"
    },
    "Bromodichloromethane": {
        "mw_g_mol": 163.83,
        "conc_ppmv": 3.1,
        "rating": "C"
    },
    "Butane": {
        "mw_g_mol": 58.12,
        "conc_ppmv": 5,
        "rating": "C"
    },
    "Carbon disulfidea": {
        "mw_g_mol": 76.13,
        "conc_ppmv": 0.58,
        "rating": "C"
    },
    "Carbon monoxideb": {
        "mw_g_mol": 28.01,
        "conc_ppmv": "110e",
        "rating": "Minimally Representativef"
    },
    "Carbon tetrachloridea": {
        "mw_g_mol": 153.84,
        "conc_ppmv": "4.0x10-3",
        "rating": "B"
    },
    "Carbonyl sulfidea": {
        "mw_g_mol": 60.07,
        "conc_ppmv": 0.49,
        "rating": "D"
    },
    "Chlorobenzenea": {
        "mw_g_mol": 112.56,
        "conc_ppmv": 0.25,
        "rating": "C"
    },
    "Chlorodifluoromethane": {
        "mw_g_mol": 86.47,
        "conc_ppmv": 1.3,
        "rating": "C"
    },
    "Chloroethane (ethyl chloride)a": {
        "mw_g_mol": 64.52,
        "conc_ppmv": 1.3,
        "rating": "B"
    },
    "Chloroforma": {
        "mw_g_mol": 119.39,
        "conc_ppmv": "3.0x10-2",
        "rating": "B"
    },
    "Chloromethane": {
        "mw_g_mol": 50.49,
        "conc_ppmv": 1.2,
        "rating": "B"
    },
    "Dichlorobenzenec": {
        "mw_g_mol": 147,
        "conc_ppmv": 0.21,
        "rating": "E"
    },
    "Dichlorodifluoromethane": {
        "mw_g_mol": 120.91,
        "conc_ppmv": 16,
        "rating": "A"
    },
    "Dichlorofluoromethane": {
        "mw_g_mol": 102.92,
        "conc_ppmv": 2.6,
        "rating": "D"
    },
    "Dichloromethane (methylene chloride)a": {
        "mw_g_mol": 84.94,
        "conc_ppmv": 14,
        "rating": "A"
    },
    "Dimethyl sulfide (methyl sulfide)": {
        "mw_g_mol": 62.13,
        "conc_ppmv": 7.8,
        "rating": "C"
    },
    "Ethane": {
        "mw_g_mol": 30.07,
        "conc_ppmv": 890,
        "rating": "C"
    },
    "Ethanol": {
        "mw_g_mol": 46.08,
        "conc_ppmv": 27,
        "rating": "E"
    },
    "Ethyl mercaptan (ethanethiol)": {
        "mw_g_mol": 62.13,
        "conc_ppmv": 2.3,
        "rating": "D"
    },
    "Ethylbenzenea": {
        "mw_g_mol": 106.16,
        "conc_ppmv": 4.6,
        "rating": "B"
    },
    "Ethylene dibromide": {
        "mw_g_mol": 187.88,
        "conc_ppmv": "1.0x10-3",
        "rating": "E"
    },
    "Fluorotrichloromethane": {
        "mw_g_mol": 137.38,
        "conc_ppmv": 0.76,
        "rating": "B"
    },
    "Hexanea": {
        "mw_g_mol": 86.18,
        "conc_ppmv": 6.6,
        "rating": "B"
    },
    "Hydrogen sulfide": {
        "mw_g_mol": 34.08,
        "conc_ppmv": 36,
        "rating": "B"
    },
    "Mercury (total)a,d": {
        "mw_g_mol": 200.61,
        "conc_ppmv": "2.9x10-4",
        "rating": "E"
    },
    "Methyl ethyl ketonea": {
        "mw_g_mol": 72.11,
        "conc_ppmv": 7.1,
        "rating": "A"
    },
    "Methyl isobutyl ketonea": {
        "mw_g_mol": 100.16,
        "conc_ppmv": 1.9,
        "rating": "B"
    },
    "Methyl mercaptan": {
        "mw_g_mol": 48.11,
        "conc_ppmv": 2.5,
        "rating": "C"
    },
    "Pentane": {
        "mw_g_mol": 72.15,
        "conc_ppmv": 3.3,
        "rating": "C"
    },
    "Perchloroethylene (tetrachloroethylene)a": {
        "mw_g_mol": 165.83,
        "conc_ppmv": 3.7,
        "rating": "B"
    },
    "Propane": {
        "mw_g_mol": 44.09,
        "conc_ppmv": 11,
        "rating": "B"
    },
    "t-1,2-dichloroethene": {
        "mw_g_mol": 96.94,
        "conc_ppmv": 2.8,
        "rating": "B"
    },
    "Trichloroethylene (trichloroethene)a": {
        "mw_g_mol": 131.4,
        "conc_ppmv": 2.8,
        "rating": "B"
    },
    "Vinyl chloridea": {
        "mw_g_mol": 62.5,
        "conc_ppmv": 7.3,
        "rating": "B"
    },
    "Xylenesa": {
        "mw_g_mol": 106.16,
        "conc_ppmv": 12,
        "rating": "B"
    }
}

AP42_TABLE_2_4_2 = [
    {
        "pollutant": "Pollutant",
        "mw_g_mol": "Molecular Weight",
        "conc_ppmv": "Default Concentration (ppmv)",
        "rating": "Emission Factor Rating"
    },
    {
        "pollutant": "Benzeneb - Co-disposal",
        "mw_g_mol": 78.11,
        "conc_ppmv": 11,
        "rating": "D"
    },
    {
        "pollutant": "Benzeneb - No or Unknown co-disposal",
        "mw_g_mol": 78.11,
        "conc_ppmv": 1.9,
        "rating": "B"
    },
    {
        "pollutant": "NMOC (as hexane)c - Co-disposal (pre 1992) d",
        "mw_g_mol": 86.18,
        "conc_ppmv": 2400,
        "rating": "D"
    },
    {
        "pollutant": "NMOC (as hexane)c - No or Unknown co-disposal (pre 1992) d",
        "mw_g_mol": 86.18,
        "conc_ppmv": 600,
        "rating": "B"
    },
    {
        "pollutant": "NMOC (as hexane) c - No or Unknown co-disposal (1992+)d",
        "mw_g_mol": 86.18,
        "conc_ppmv": "550e",
        "rating": "Moderately Representativef"
    },
    {
        "pollutant": "Tolueneb - Co-disposal",
        "mw_g_mol": 92.13,
        "conc_ppmv": 170,
        "rating": "D"
    },
    {
        "pollutant": "Tolueneb - No or Unknown co-disposal",
        "mw_g_mol": 92.13,
        "conc_ppmv": 39,
        "rating": "A"
    }
]

AP42_UNCONTROLLED_PPMV_FACTORS = {
    "CARBON MONOXIDE": 105,
    "TOTAL NON-METHANE ORGANIC COMPOUNDS, AS HEXANE - 1992+": 552
}
