"""Build the Scentinel gas database from scraped AP-42 data.

Reads docs/data/ap-42-chapter-2-section-4-tables-final.xlsx (downloaded from EPA)
and emits src/scentinel/core/gas_defaults.py with cited defaults.

Usage:
    .venv/bin/python scripts/build_gas_data.py
"""

from __future__ import annotations

import json
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parent.parent
XLSX = ROOT / "docs" / "data" / "ap-42-chapter-2-section-4-tables-final.xlsx"
OUT = ROOT / "src" / "scentinel" / "core" / "gas_defaults.py"

# Physical properties at 25 C, 1 atm. Diffusivity sources in docs/references.md.
GAS_PROPERTIES = {
    "CO": {
        "name": "Carbon monoxide",
        "mw_g_mol": 28.01,
        "diffusivity_m2_s": 2.0e-5,
    },
    "CH4": {
        "name": "Methane",
        "mw_g_mol": 16.04,
        "diffusivity_m2_s": 2.2e-5,
    },
    "VOC": {
        "name": "Non-methane organic compounds (as hexane proxy)",
        "mw_g_mol": 86.18,
        "diffusivity_m2_s": 8.7e-6,
    },
    "H2S": {
        "name": "Hydrogen sulfide",
        "mw_g_mol": 34.08,
        "diffusivity_m2_s": 1.6e-5,
    },
}

# Source concentrations, ppmv unless noted. Values cross-checked against the
# final AP-42 Ch.2.4 PDF (docs/data/c2s4_2024_final.pdf).
SOURCE_DEFAULTS = {
    "CO": {
        "conc_ppmv": 105,
        "basis": "AP-42 Final Factors: uncontrolled CO, parts per million (ref 98)",
        "rating": "Minimally representative",
    },
    "CH4": {
        "fraction_by_volume": 0.5,
        "basis": "EPA LMOP: LFG ~50% CH4 by volume",
        "alternate_fraction": 0.55,
        "alternate_basis": "AP-42 Ch.2.4 steady-state: ~55% CH4, 40% CO2, 5% N2",
    },
    "VOC": {
        "conc_ppmv": 550,
        "basis": "AP-42 Table 2.4-2: NMOC as hexane, no/unknown co-disposal, 1992+",
        "alternate_conc_ppmv": 2400,
        "alternate_basis": "AP-42 Table 2.4-2: NMOC as hexane, co-disposal (pre 1992)",
    },
    "H2S": {
        "conc_ppmv": 36,
        "basis": "AP-42 Table 2.4-1: default concentration",
        "rating": "B",
    },
}


def read_ap42() -> dict:
    wb = openpyxl.load_workbook(XLSX, data_only=True)

    ws = wb["Final Factors"]
    ppmv_factors = {}
    for row in ws.iter_rows(values_only=True):
        if not row or not row[2] or not row[3]:
            continue
        units = str(row[3]).strip().upper()
        activity = str(row[4] or "").upper()
        if units == "PARTS" and "MILLION PARTS" in activity:
            # column 7 is "Factor"; column 6 is "Composite Test Rating"
            ppmv_factors[str(row[2]).strip()] = row[7]

    trace = {}
    ws2 = wb["Table 2.4-1"]
    for row in ws2.iter_rows(values_only=True):
        if row and row[0] and row[1] is not None:
            trace[str(row[0]).strip()] = {
                "mw_g_mol": row[1],
                "conc_ppmv": row[2],
                "rating": row[3],
            }

    table_242 = []
    ws3 = wb["Table 2.4-2"]
    for row in ws3.iter_rows(values_only=True):
        if row and row[0] and row[1] is not None and row[2] is not None:
            table_242.append(
                {
                    "pollutant": str(row[0]).strip(),
                    "mw_g_mol": row[1],
                    "conc_ppmv": row[2],
                    "rating": row[3],
                }
            )

    return {"ppmv_factors": ppmv_factors, "trace_compounds": trace, "table_242": table_242}


def build() -> dict:
    ap42 = read_ap42()

    lines = [
        '"""Auto-generated by scripts/build_gas_data.py. Do not edit by hand."""',
        "",
        "# Data sources:",
        "#   EPA AP-42 Ch.2.4 final (Aug 2024): docs/data/c2s4_2024_final.pdf",
        "#   EPA AP-42 tables: docs/data/ap-42-chapter-2-section-4-tables-final.xlsx",
        "#   EPA LMOP landfill gas basics: https://www.epa.gov/lmop/basic-information-about-landfill-gas",
        "",
        f"GAS_PROPERTIES = {json.dumps(GAS_PROPERTIES, indent=4)}",
        "",
        f"SOURCE_DEFAULTS = {json.dumps(SOURCE_DEFAULTS, indent=4)}",
        "",
        f"AP42_TRACE_COMPOUNDS = {json.dumps(ap42['trace_compounds'], indent=4)}",
        "",
        f"AP42_TABLE_2_4_2 = {json.dumps(ap42['table_242'], indent=4)}",
        "",
        f"AP42_UNCONTROLLED_PPMV_FACTORS = {json.dumps(ap42['ppmv_factors'], indent=4)}",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"[saved] {OUT}")
    return SOURCE_DEFAULTS


if __name__ == "__main__":
    result = build()
    print(json.dumps(result, indent=2))
